name: Docker Publication

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      # Connexion au GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Construction de l’image du Docker
      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} . || { echo "Docker build failed"; exit 1; }

      - name: Tag Docker images
        run: |
          docker tag myapp:${{ github.sha }} mydockerhubuser/myapp:latest || { echo "Tagging failed"; exit 1; }
          docker tag myapp:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/mini_projet_cloudcomputing/myapp:latest || { echo "Tagging failed"; exit 1; }

      # Publication de l’image sur Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push mydockerhubuser/myapp:latest || { echo "Push to Docker Hub failed"; exit 1; }

      # Publication de l’image sur GHCR 
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/myapp:latest || { echo "Push to GHCR failed"; exit 1; }
