name: Docker Build and Publish
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .

      - name: Tag Docker images
        run: |
          docker tag myapp:${{ github.sha }} mydockerhubuser/myapp:latest
          docker tag myapp:${{ github.sha }} ghcr.io/${{ github.repository }}/myapp:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push mydockerhubuser/myapp:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/myapp:latest
