name: Docker Publication

on:
  push:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Vérification du dépôt
      - name: Check out repository code
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # dépendances
      - name: Install dependencies
        run: npm install

      # compilation de l'application
      - name: Build the application
        run: npm run build  

      # exécution des tests unitaires
      - name: Run unit tests
        run: npm test
        env:
          CI: true  
